services:
  postgres:
    image: postgres:16.1
    container_name: shareit-db
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    restart: always